package frames;

import listeners.ListenerMenuImagen;
import listeners.ListenerMenuEspacial;
import listeners.ListenerMenuHistograma;

/**
 *
 * @author artur
 */
public class JFramePrincipal extends javax.swing.JFrame 
{

    /**
     * @return the JIFM
     */
    public JInternalFrameModificar getJIFM() 
    {
        return JIFM;
    }

    /**
     * @param JIFM the JIFM to set
     */
    public void setJIFM(JInternalFrameModificar JIFM) 
    {
        this.JIFM = JIFM;
    }
    private JInternalFrameModificar JIFM;
    private JInternalFrameCopiar JIFC;
    private JInternalFrameGraficaHistograma JIFGH;
    private JInternalFrameFiltros JIFFEG;
    private JInternalFrameFiltros JIFFNG;
    private JInternalFrameFiltros JIFFBN;
    
    //Imagen
    private JInternalFrameImagen JIFI;
    
    public JFramePrincipal() 
    {
        initComponents();
        jMenuItem1.addActionListener(new ListenerMenuImagen(this));
        jMenuItem2.addActionListener(new ListenerMenuEspacial(this));
        jMenuItem3.addActionListener(new ListenerMenuEspacial(this));
        jMenuItem4.addActionListener(new ListenerMenuHistograma(this));
        jMenuItem5.addActionListener(new ListenerMenuEspacial(this));
        jMenuItem6.addActionListener(new ListenerMenuEspacial(this));
        jMenuItem7.addActionListener(new ListenerMenuEspacial(this));
        
        JIFM = null;
        JIFC = null;
        JIFGH = null;
        JIFI = null;
        
        JIFFEG = null;
        JIFFNG = null;
        JIFFBN = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_AbrirImagen = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu_Modificar = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1245, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );

        jMenu_AbrirImagen.setText("Imagen");

        jMenuItem1.setText("Abrir Imagen");
        jMenu_AbrirImagen.add(jMenuItem1);

        jMenuBar1.add(jMenu_AbrirImagen);

        jMenu_Modificar.setText("Espacial");

        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu_Modificar.add(jMenuItem2);

        jMenuItem3.setText("Copiar pixeles");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu_Modificar.add(jMenuItem3);

        jMenuItem5.setText("Escala Grises");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu_Modificar.add(jMenuItem5);

        jMenuItem6.setText("Negativo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu_Modificar.add(jMenuItem6);

        jMenuItem7.setText("Blanco y negro");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu_Modificar.add(jMenuItem7);

        jMenuBar1.add(jMenu_Modificar);

        jMenu1.setText("Histograma");

        jMenuItem4.setText("Grafica Histograma");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu jMenu_AbrirImagen;
    private javax.swing.JMenu jMenu_Modificar;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jDesktopPanePrincipal
     */
    public javax.swing.JDesktopPane getjDesktopPanePrincipal() {
        return jDesktopPanePrincipal;
    }

    /**
     * @param jDesktopPanePrincipal the jDesktopPanePrincipal to set
     */
    public void setjDesktopPanePrincipal(javax.swing.JDesktopPane jDesktopPanePrincipal) {
        this.jDesktopPanePrincipal = jDesktopPanePrincipal;
    }

    /**
     * @return the JIFC
     */
    public JInternalFrameCopiar getJIFC() {
        return JIFC;
    }

    /**
     * @param JIFC the JIFC to set
     */
    public void setJIFC(JInternalFrameCopiar JIFC) {
        this.JIFC = JIFC;
    }

    /**
     * @return the JIFGH
     */
    public JInternalFrameGraficaHistograma getJIFGH() {
        return JIFGH;
    }

    /**
     * @param JIFGH the JIFGH to set
     */
    public void setJIFGH(JInternalFrameGraficaHistograma JIFGH) 
    {
        this.JIFGH = JIFGH;
    }

    /**
     * @return the JIFI
     */
    public JInternalFrameImagen getJIFI() 
    {
        return JIFI;
    }

    /**
     * @param JIFI the JIFI to set
     */
    public void setJIFI(JInternalFrameImagen JIFI) {
        this.JIFI = JIFI;
    }

    /**
     * @return the JIFFEG
     */
    public JInternalFrameFiltros getJIFFEG() {
        return JIFFEG;
    }

    /**
     * @param JIFFEG the JIFFEG to set
     */
    public void setJIFFEG(JInternalFrameFiltros JIFFEG) {
        this.JIFFEG = JIFFEG;
    }

    /**
     * @return the JIFFNG
     */
    public JInternalFrameFiltros getJIFFNG() {
        return JIFFNG;
    }

    /**
     * @param JIFFNG the JIFFNG to set
     */
    public void setJIFFNG(JInternalFrameFiltros JIFFNG) {
        this.JIFFNG = JIFFNG;
    }

    /**
     * @return the JIFFBN
     */
    public JInternalFrameFiltros getJIFFBN() {
        return JIFFBN;
    }

    /**
     * @param JIFFBN the JIFFBN to set
     */
    public void setJIFFBN(JInternalFrameFiltros JIFFBN) {
        this.JIFFBN = JIFFBN;
    }
}
