/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import herramientas.Grafica;
import static herramientas.herramientas.toBufferedImage;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;

/**
 *
 * @author artur
 */
public class JInternalFrameGraficaHistograma extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameGraficaHistograma
     */
    private JInternalFrameImagen JFI;
    
    public JInternalFrameGraficaHistograma(JInternalFrameImagen JFI) 
    {
        this.JFI = JFI;
        initComponents();
        
        this.jButton_Graficar.addActionListener(new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent ae) 
            {
                generarGrafica(0);
            }
        });
        
        this.jButton_GraficarV.addActionListener(new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent ae) 
            {
                generarGrafica(1);
            }
        });
    }
    
    public void generarGrafica(int graficas)
    {
        int[] r = new int[256];
        int[] g = new int[256];
        int[] b = new int[256];
        
        BufferedImage bufferimagen = toBufferedImage(getJFI().getImagenSecundaria());
        
        int width = getJFI().getImagenSecundaria().getWidth(this);
        int height = getJFI().getImagenSecundaria().getHeight(this);
        
        for(int x = 0; x < width; x++)
        {
            for(int y = 0; y < height; y++)
            {
                Color c = new Color(bufferimagen.getRGB(x, y));
                
                r[c.getRed()]++;
                g[c.getGreen()]++;
                b[c.getBlue()]++;
            }
        }

        if(graficas == 0)
        {
            Grafica grafica = new Grafica("Valor RGB","Num","RGB");
            grafica.agregarSerie("R",r);
            grafica.agregarSerie("B",b);
            grafica.agregarSerie("G",g);
            grafica.crearGrafica();
            grafica.muestraGrafica();
        }
        else
        {
            Grafica gR = new Grafica("Valor RGB","Num","R");
            gR.agregarSerie("R",r);
            //gR.agregarSerie("B",b);
            //gR.agregarSerie("G",g);
            gR.crearGrafica();
            gR.muestraGrafica();

            Grafica gG = new Grafica("Valor RGB","Num","G");
            //gG.agregarSerie("R",r);
            //gG.agregarSerie("B",b);
            gG.agregarSerie("G",g);
            gG.crearGrafica();
            gG.muestraGrafica();

            Grafica gB = new Grafica("Valor RGB","Num","B");
            //gB.agregarSerie("R",r);
            gB.agregarSerie("B",b);
            //gB.agregarSerie("G",g);
            gB.crearGrafica();
            gB.muestraGrafica();
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Graficar = new javax.swing.JButton();
        jButton_GraficarV = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jButton_Graficar.setText("Graficar");
        jButton_Graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GraficarActionPerformed(evt);
            }
        });

        jButton_GraficarV.setText("Graficar Separadas");
        jButton_GraficarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GraficarVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_GraficarV, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_GraficarV, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GraficarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_GraficarActionPerformed

    private void jButton_GraficarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GraficarVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_GraficarVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Graficar;
    private javax.swing.JButton jButton_GraficarV;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the JFI
     */
    public JInternalFrameImagen getJFI() {
        return JFI;
    }

    /**
     * @param JFI the JFI to set
     */
    public void setJFI(JInternalFrameImagen JFI) {
        this.JFI = JFI;
    }
}
